name: "Unit Test"

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]
  merge_group:

jobs:
  go-test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Install Go
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version-file: script/go.mod
    - name: Go Test (script)
      run: |
        cd script
        go test -v -race ./...
    - name: Go Test (tests)
      run: |
        cd tests
        go test -v -race ./...
